# Generated by Django 4.1 on 2022-08-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
