# Generated by Django 4.1 on 2022-08-13 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mysite.helpers.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('file', models.FileField(blank=True, null=True, upload_to=mysite.helpers.helpers.UploadTo('post_files'))),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=mysite.helpers.helpers.UploadTo('post_imges'))),
                ('post', models.ManyToManyField(to='main.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
