# Generated by Django 4.1 on 2022-08-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_images_post_images_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
